// ==UserScript==
// @name         Gartic.io 2019 (Hacks,Mods,Cheats) - Really Working (sandbox-unblocked)
// @description  Garticio Auto Guess,Word Helper,Faster Drawer, Player Info, Faster Writer, Adblock
// @author       Never-Steal-Dont-Ban
// @namespace    Never-Steal-Dont-Ban
// @version      1.2
// @match *://gartic.io/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// @require      https://code.jquery.com/jquery-3.3.1.min.js
// ==/UserScript==
setTimeout(function() {
$('.lastRooms').append('<div style="border:2px solid black;border-radius:20px;padding:5px;background-color: rgba(255, 255, 255, 0);"><div class="containerFreespace0"></div></div>');
$('.anonymus').append('<div class="containerFreespace0"></div>');
 $('.mobileHide').html('<div style="border:2px solid black;border-radius:20px;padding:5px;background-color: rgba(255, 255, 255, 0.3);"><div class="containerFreespace11"></div></div>');
$('.containerFreespace0').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/gtEqkM" target="blank">Word Helper</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/SXUzeF\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/3ee6Lz" target="blank">Guess Trier</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/aHMmvA\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace3"></div>');
$('.containerFreespace3').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/Lb1GKp" target="blank">Inform Giver</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/Lb1GKp\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/XCNoJL" target="blank">Faster Writer</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/XCNoJL\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace5"></div>');
$('.containerFreespace5').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/6kqrgN" target="blank">Faster Drawer</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/6kqrgN\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/FGU9pC" target="blank">Auto Draw (?)</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/FGU9pC\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace7"></div>');
$('.containerFreespace7').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/aHMmvA" target="blank">Auto Guess (?)</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/28tVmw\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/GyxY6U" target="blank">Show Player Info</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/X8Lhyn\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace9"></div>');
$('.containerFreespace9').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://goo.gl/SXUzeF" target="blank">Adblock Plus+</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://goo.gl/uqFAWf\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label>');
$('.containerFreespace11').html('<div style="color:white;background-color: black;padding-top:3px;padding-bottom:3px;" id="desktopInstructions" class="menuText"><a class="menuLink" href="https://goo.gl/XCNoJL" target="_blank" style="color:orange;font-size:12px;">SLITHERE.COM</a> - <a class="menuLink" href="https://goo.gl/6kqrgN" target="_blank" style="color:orange;font-size:12px;">KRUNKERIO.NET</a> - <a class="menuLink" href="https://goo.gl/FGU9pC" target="_blank" style="color:orange;font-size:12px;">KRUNKERIO.ORG</a> - <a class="menuLink" href="https://goo.gl/SXUzeF" target="_blank" style="font-size:12px;color:white;">ZOMBSROYALEIO.ORG</a> - <a class="menuLink" href="https://goo.gl/9PX3kG" target="_blank" style="font-size:12px;color:white;">DIEPIOPLAY.COM</a> - <a class="menuLink" href="https://goo.gl/Lb1GKp" target="_blank" style="color:white;font-size:12px;">SURVIVIO.INFO</a> - <a class="menuLink" href="https://goo.gl/28tVmw" target="_blank" style="font-size:12px;color:white;">SKRIBBLIO.NET</a> - <a class="menuLink" href="https://goo.gl/E6AuWS" target="_blank" style="font-size:12px;color:white;">BONK-IO.NET</a> - <a class="menuLink" href="https://goo.gl/aHMmvA" target="_blank" style="font-size:12px;color:white;">MOPE-IO.NET</a> - <a class="menuLink" href="https://goo.gl/GyxY6U" target="_blank" style="font-size:12px;color:white;">MOPEIOGAME.COM</a> - <a class="menuLink" href="https://goo.gl/X8Lhyn" target="_blank" style="font-size:12px;color:white;">MOOMOOIOPLAY.COM</a> - <a class="menuLink" href="https://goo.gl/uqFAWf" target="_blank" style="font-size:12px;color:white;">DIEPIOPLAY.ORG</a> - <a class="menuLink" href="https://goo.gl/af7rF6" target="_blank" style="font-size:12px;color:white;">IOGAMESLIST.ORG</a> - <a class="menuLink" href="https://goo.gl/JcfvKP" target="_blank" style="color:lightgreen;font-size:12px;">SHELLSHOCKIO.ORG</a></div><div class="containerFreespace0"></div>');

    }, 0);
