// ==UserScript==
// @name         Gartic.io 2019 (Hacks,Mods,Cheats) | Unblocked Sandbox | WORMAX.ORG
// @description  Garticio Zoom and Speed Hacks, Cheats, Mods Unblocked 2019 Game Play FPS,Bots
// @author       Mr.Coder
// @namespace    Mr.Coder
// @version      1.0
// @match *://gartic.io/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// @require      https://code.jquery.com/jquery-3.3.1.min.js
// ==/UserScript==
setTimeout(function() {
$('.lastRooms').append('<div style="border:2px solid black;border-radius:20px;padding:5px;background-color: rgba(255, 255, 255, 0);"><div class="containerFreespace0"></div></div>');
$('.anonymus').append('<div class="containerFreespace0"></div>');
 $('.mobileHide').html('<div style="border:2px solid black;border-radius:20px;padding:5px;background-color: rgba(255, 255, 255, 0.3);"><div class="containerFreespace11"></div></div>');
$('.containerFreespace0').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://wormax.org" target="blank">Word Helper</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://zombsroyaleio.org\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://wormate-io.net" target="blank">Guess Trier</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://mope-io.net\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace3"></div>');
$('.containerFreespace3').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://survivio.info" target="blank">Inform Giver</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://survivio.info\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://slithere.com" target="blank">Faster Writer</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://slithere.com\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace5"></div>');
$('.containerFreespace5').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://krunkerio.net" target="blank">Faster Drawer</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://krunkerio.net\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://krunkerio.org" target="blank">Auto Draw (?)</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://krunkerio.org\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace7"></div>');
$('.containerFreespace7').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://mope-io.net" target="blank">Auto Guess (?)</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://skribbl-io.net\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label> <-> <a style="font-weight:bold;color:black;font-size:14px;" href="https://mopeiogame.com" target="blank">Show Player Info</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://moomooioplay.com\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label><div class="containerFreespace9"></div>');
$('.containerFreespace9').html('<a style="font-weight:bold;color:black;font-size:14px;" href="https://zombsroyaleio.org" target="blank">Adblock Plus+</a> <label style="padding-left: 2px;" class=\'switch\'><input type=\'checkbox\' onchange="window.open(\'https://diepioplay.org\', \'_blank\', \'location=yes,scrollbars=yes,status=yes,height=570,width=520\');"><span class=\'slider\'></span></label>');
$('.containerFreespace11').html('<div style="color:white;background-color: black;padding-top:3px;padding-bottom:3px;" id="desktopInstructions" class="menuText"><a class="menuLink" href="https://slithere.com" target="_blank" style="color:orange;font-size:12px;">SLITHERE.COM</a> - <a class="menuLink" href="https://krunkerio.net" target="_blank" style="color:orange;font-size:12px;">KRUNKERIO.NET</a> - <a class="menuLink" href="https://krunkerio.org" target="_blank" style="color:orange;font-size:12px;">KRUNKERIO.ORG</a> - <a class="menuLink" href="https://zombsroyaleio.org" target="_blank" style="font-size:12px;color:white;">ZOMBSROYALEIO.ORG</a> - <a class="menuLink" href="https://diepioplay.com" target="_blank" style="font-size:12px;color:white;">DIEPIOPLAY.COM</a> - <a class="menuLink" href="https://survivio.info" target="_blank" style="color:white;font-size:12px;">SURVIVIO.INFO</a> - <a class="menuLink" href="https://skribbl-io.net" target="_blank" style="font-size:12px;color:white;">SKRIBBLIO.NET</a> - <a class="menuLink" href="https://bonk-io.net" target="_blank" style="font-size:12px;color:white;">BONK-IO.NET</a> - <a class="menuLink" href="https://mope-io.net" target="_blank" style="font-size:12px;color:white;">MOPE-IO.NET</a> - <a class="menuLink" href="https://mopeiogame.com" target="_blank" style="font-size:12px;color:white;">MOPEIOGAME.COM</a> - <a class="menuLink" href="https://moomooioplay.com" target="_blank" style="font-size:12px;color:white;">MOOMOOIOPLAY.COM</a> - <a class="menuLink" href="https://diepioplay.org" target="_blank" style="font-size:12px;color:white;">DIEPIOPLAY.ORG</a> - <a class="menuLink" href="https://iogameslist.org" target="_blank" style="font-size:12px;color:white;">IOGAMESLIST.ORG</a> - <a class="menuLink" href="https://shellshockio.org" target="_blank" style="color:lightgreen;font-size:12px;">SHELLSHOCKIO.ORG</a></div><div class="containerFreespace0"></div>');

    }, 0);
